project:
  type: book
  render:
  - index.qmd
  - day1.qmd
  - rstudio.qmd
  - r.qmd
  - projects.qmd
  - quarto.qmd
  - git.qmd
  - projrsimple.qmd
  - prac1.qmd
  - day2.qmd
  - varAssign.qmd
  - logic.qmd
  - loops.qmd
  - Vectos.qmd
  output-dir: docs
book:
  title: Statistical Computing
  sidebar:
    border: true
    background: light
  navbar:
    search: true
    background: light
  chapters:
  - index.qmd
  - part: day1.qmd
    chapters:
    - rstudio.qmd
    - projects.qmd
    - quarto.qmd
    - git.qmd
    - projrsimple.qmd
    - r.qmd
    - prac1.qmd
  - part: day2.qmd
    chapters: 
    - varAssign.qmd
    - logic.qmd
    - loops.qmd
    - Vectors.qmd
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: right

